apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythonapp
  name: pythonapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: pythonapp
  sessionAffinity: None
  type: ClusterIP